site_name: Foundations of Omics
repo_url: https://github.com/Sydney-Informatics-Hub/Omics-Study-Designs-and-Data-Interpretation
repo_name: Sydney-Informatics-Hub/Omics-Study-Designs-and-Data-Interpretation

nav:
  # Landing page
  - Home: index.md
  - Module 1: 
    - Module 1.1 Omics landscape: module1-1.md
    - Module 1.2 Experimental workflow: 
      - Overview: module1-2-0.md
      - Stage 1 - Design: module1-2-1.md
      - Stage 2 - Data acquisition: module1-2-2.md
      - Stage 3 - Preprocessing: module1-2-3.md
      - Stage 4 - Analysis: module1-2-4.md
      - Stage 5 - Reporting: module1-2-5.md
      - Activity: module1-2-6.md
  - Module 2: 
      - Overview: module2-0.md
      - Module 2.1 Accuracy and interpretability:
          - Choosing a platform: module2-1.md
          - Confounding and batch: module2-2.md
          - Measurement and metadata: module2-3.md
      - Module 2.2 Power and cost:
          - Sample size: module2-4.md
          - Spending the budget: module2-5.md
      - Module 2.3 Generalisability:
          - Who the findings apply to: module2-6.md
      - Module 2.4 Putting it together: module2-7.md

  - References: further-reading.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
    - navigation.tabs          
    - navigation.tabs.sticky   
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - toc:
      toc_depth: 2

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57

copyright: >
  © 2026 Copyright (c) 2025 Sydney Informatics Hub, University of Sydney.
  <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>
