site_name: Foundations of Omics
repo_url: https://github.com/Sydney-Informatics-Hub/Omics-Study-Designs-and-Data-Interpretation
repo_name: Sydney-Informatics-Hub/Omics-Study-Designs-and-Data-Interpretation

nav:
  # Landing page
  - Home: index.md
  - Introduction: Introduction.md
  - Module 1: 
    - The 'omics landscape: Day1/module1-1.md
    - Why 'omics studies fail: Day1/module1-2.md
  - Module 2: 
    - Core statistical properties: Day1/module2-1.md
    - Sparsity and zero inflation: Day1/module2-2.md
    - Compositionality: Day1/module2-3.md
    - Classical statistics struggle with omics: Day1/module2-4.md
  - Module 3:
    - Module3: Day1/module3.md
    - Randomisation: Day1/module3-1.md
    - Sparsity and zero inflation: Day1/module3-2.md
    - Compositionality: Day1/module3-3.md
    - Classical statistics struggle with omics: Day1/module3-4.md
  - Module4: Day2/module4.md
  - Module5: Day2/module5.md
  - Module6: Day2/module6.md
  - Further reading: further-reading.md 
  # Example top-level page
  #- Setup: setup.md
  # Example nested page
  # - Part 1:
  #   - Introduction: part1/intro.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
    - navigation.tabs          # by Amarinder Thind
    - navigation.tabs.sticky   # by Amarinder Thind
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57

copyright: >
  © 2026 Copyright (c) 2025 Sydney Informatics Hub, University of Sydney.
  <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>