site_name: Foundations of Omics
repo_url: https://github.com/Sydney-Informatics-Hub/Omics-Study-Designs-and-Data-Interpretation
repo_name: Sydney-Informatics-Hub/Omics-Study-Designs-and-Data-Interpretation

nav:
  # Landing page
  - Home: index.md
  - Introduction: Introduction.md
  - Module 1: 
    - The omics landscape: content/module1-1.md
    - Study design factors: content/module1-2-0.md
    - Design: content/module1-2-1.md
    - Sample acquisition: content/module1-2-2.md
    - Preprocessing: content/module1-2-3.md
    - Analysis: content/module1-2-4.md
    - Reporting: content/module1-2-5.md
    - Activity: content/module1-2-6.md
    - Study design factors (old): content/module1-2.md
  - Module 2:
    - Omics Platforms: content/module-nm2.2.md
    - Sample Size: content/module-nm2.3-short.md

  - Module 2 (old): 
    - Data types & platforms: content/module2-1.md
    - Detection limits & budget: content/module2-2.md
    - Sparsity and zero inflation: content/module2-3.md
    - Compositionality: content/module2-4.md
    - Classical statistics struggle with omics: content/module2-5.md

  - Module 3 (old):
    - Randomisation: content/module3-1.md
    - Replication: content/module3-2.md
    - Sample Size: content/module3-3.md
    - Study Design: content/module3-4.md
    - Meta Data: content/module3-5.md
  - References: further-reading.md
  
  # Example top-level page
  #- Setup: setup.md
  # Example nested page
  # - Part 1:
  #   - Introduction: part1/intro.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
    - navigation.tabs          # by Amarinder Thind
    - navigation.tabs.sticky   # by Amarinder Thind
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57

copyright: >
  © 2026 Copyright (c) 2025 Sydney Informatics Hub, University of Sydney.
  <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>
